pub mod attention;
pub mod blocksparse;
pub mod grouped;
pub mod block;
pub mod compression;
pub mod config;
pub mod growable_optim;
pub mod moe;
pub mod norm;
pub mod output;
pub mod persist;
pub mod registry;
pub mod slab;
pub mod sparse_routing;
pub mod substrate;

pub use attention::CapKeyedMha;
pub use blocksparse::{apply_blocksparse_projection, blocksparse_routing, BlockSparseRouting};
pub use grouped::{grouped_matmul, GroupedMatmulCuda};
pub use block::{CapNativeBlock, CapNativeBlockConfig};
pub use compression::{AutoInputs, CompressionConfig, CompressionDType, DeviceKind, RoutingMode};
pub use config::{CapLayer1Config, CapNativeConfig};
pub use growable_optim::GrowableAdamW;
pub use moe::CapMoeMlp;
pub use norm::{top_k_softmax, CapKeyedRmsNorm};
pub use output::CapKeyedOutput;
pub use persist::{load_checkpoint, save_checkpoint};
pub use registry::{CapDecision, CapRecord, CommitRegistry};

pub use substrate::{CapNativeBuilder, CapNativeSubstrate};
